### ISSUE TITLE
Options box positioning problem

### ISSUE THREAD

**Issue by UKDeveloper99** [gs-akhan/react-native-select#10]
I tried this out and when I click to open the options list the container box for all the options aligns to bottom right hand corner of the screen. Even though the main box containing the default text etc is positioned near the top of the view. It creates a white box between the two of them.

The positioning of the options list box seems to be completely broken. This is when I compared it to the dropdown module from Alinz, you're contributing to that right. So something you changed must of broken the items dropdown.

If it helps I was using the exact code from the example on the readme. Also I placed my dropdown box in the renderScene function of a navigator, rather than the usual render() function. So that may be related.

The platform was Android and the device orientation was portrait.

Hopefully that helps to replicate the issue.

Screenshots:
BEFORE
![screenshot_2016-03-11-14-13-15](https://cloud.githubusercontent.com/assets/11443031/13704536/542a1c5c-e794-11e5-89f5-dbad9b796597.png)
AFTER
![screenshot_2016-03-11-14-12-52](https://cloud.githubusercontent.com/assets/11443031/13704535/54225008-e794-11e5-82ab-215ae71bbb42.png)

the whitebox is hard to see in the screenshot but it's much more visible on the device. Basically the items aren't rendering where they should be. The white box is also overlapping the main box that's why you can't see it in the after screenshot

**Comment by gs-akhan** [comment]
I will try to replicate this.. But a screen shot would be awesome , anyways
I will try it out ..
Thanks

**Comment by UKDeveloper99** [comment]
I added screenshots

**Comment by UKDeveloper99** [comment]
Make sure you create the dropdown in the renderScene function from navigator

**Comment by gs-akhan** [comment]
Got it .. I haven't tested this dropdown in renderScene of Navigator though.

Will def test it out.

Thanks

**Comment by UKDeveloper99** [comment]
you will have to change the refs to refs of navigator. 
e.g.
this.refs.navigator.refs['SELECT1'];

**Comment by kelvinaliyanto** [comment]
@gs-akhan FYI, this positioning problem also persists when there is scrollview involved.

**Comment by birat-bade** [comment]
Is there any updates on this issue?? I am also facing the same problem.

From looking around the code I think the problem is in overlay.js. Please take a look.

**Comment by sajjidakr** [comment]
Positioning of the option panel is a major issue , i am also facing it

**Comment by UKDeveloper99** [comment]
Here's a simple tip @kelvinaliyanto @birat-bade @sajjidakr 

Don't use this plugin....

It's poorly coded and poorly maintained. This guy took over and he hasn't committed anything since June. There you have it. Look elsewhere. Over and out.
