### ISSUE TITLE
Menu starts in full height on my android phone.

### ISSUE THREAD

**Issue by SimplyLinn** [gs-akhan/react-native-select#15]
Most of the times, the first frame when opening the select menu is in full height, making the select menu seem jerky.

I tracked down this issue to line 32 in items.js

You should initialize the value to 1, instead of 0, as 0 makes React render the view as if it had null height (-> full height), which results in this jerky behaviour.

(I did not feel like forking this project, committing/pushing a change and making a pull-request for a 1-character change.)

**Comment by gs-akhan** [comment]
Thank you. I will fix this.
Cheers

**Comment by abuammar** [comment]
gs-khan have u fixed it ?
list has full height with every on screen hidden.

**Comment by gs-akhan** [comment]
Its fixed. please update and check it out once..

**Comment by abuammar** [comment]
thanks
