### ISSUE TITLE
ScrollView "viewConfig" is not defined

### ISSUE THREAD

**Issue by luruozhou** [gs-akhan/react-native-select#22]
when I run the example on android with React Native version 0.37, ,I met this problem, how to deal with it?

**Comment by gs-akhan** [comment]
HI,
Do you get same issue on IOS ?

**Comment by luruozhou** [comment]
sorry, I haven't test it on iOS, I got another way to use native picker with the help of iOS developer.

**Comment by gs-akhan** [comment]
Cool. Closing then
