### ISSUE TITLE
Please add the original creator to readme

### ISSUE THREAD

**Issue by kennethpdev** [gs-akhan/react-native-select#25]
I know this is a forked version of this [repo](https://github.com/alinz/react-native-dropdown). Atl east give the guy a credit in the readme file :)

**Comment by gs-akhan** [comment]
I am admin to that repo as well. We are buddies btw. :)
Thanks

**Comment by kennethpdev** [comment]
Good to know. However the old one works instead of this one. When I tap on the dropdown, everything just go white.
![bug](https://cloud.githubusercontent.com/assets/1641990/21965501/45f74d9c-db9c-11e6-8ee6-7b4ff67dc61e.gif)

**Comment by gs-akhan** [comment]
Did you try this simpler version [chooser](https://github.com/gs-akhan/react-native-chooser) This is bullet proof in terms of issue and has Simplest API.. It is just like Html <select>
Try it,
https://github.com/gs-akhan/react-native-chooser
