### ISSUE TITLE
Install without RNPM

### ISSUE THREAD

**Issue by BrunoQuaresma** [gs-akhan/react-native-select#26]
RNPM is deprecated. Soo, how can i install wihout use? I try by manual way but when i change the main activity it brokens react-native-vector-itens

**Comment by gs-akhan** [comment]
Hi,
Did you try `react-native link` ?

**Comment by BrunoQuaresma** [comment]
I'm using other package. When I back to use it I post here if it works.

**Comment by gs-akhan** [comment]
So it is working fine now ?
