### ISSUE TITLE
What is the difference between react-native-select and react-native-drop?

### ISSUE THREAD

**Issue by walter211** [gs-akhan/react-native-select#5]
I see these two rn lib are similiar, are they all the same?

**Comment by gs-akhan** [comment]
Yes. This one opens the dropdown in an overlay occupying full screen. and other one opens the dropdown just like html select tag..
Thanks.

**Comment by gs-akhan** [comment]
btw. You this works consistently on both Android and IOS. The rn-drop has issues with Android. And we are trying to fix that there as well..

**Comment by walter211** [comment]
Another question，I tried to add style to OptionList, both attribute style and textStyle failed, I do not want to modify the lib, is there any other way to do this?

**Comment by gs-akhan** [comment]
Ouch. That looks like a bug.. If you can fix it .please send a pr. Thanks

**Comment by gs-akhan** [comment]
@walter211  please use `overlayStyles` for styling the optionList

Thanks
