### ISSUE TITLE
Item value in Option

### ISSUE THREAD

**Issue by marcosinigaglia** [gs-akhan/react-native-select#7]
Hi, is possible to have a different props for display text and selected value in the Option element?
Thanks, Marco.

**Comment by gs-akhan** [comment]
Hi. Yes you can pass specific styles to Option Text
https://github.com/gs-akhan/react-native-select#option

Hope it helps .. Thanks

**Comment by kelvinaliyanto** [comment]
Hi @gs-akhan, what he meant is that passing a value assigned to the option, instead of the displayed text. Similar to how we can assign a value to an option in HTML select.

**Comment by gs-akhan** [comment]
@kelvinaliyanto , I am sorry.. Yes you can do that. you can pass value as prop to <option>
I need to update the read me !!  Doing right away 

Thanks

**Comment by gs-akhan** [comment]
@marcosinigaglia @kelvinaliyanto 
https://github.com/gs-akhan/react-native-select#option

Updated, thanks
