### ISSUE TITLE
Items taking full height in android.

### ISSUE THREAD

**Issue by sankhadeeproy007** [gs-akhan/react-native-select#8]
Hi, thanks for this lovely component. I just have one problem. I've tried the example, but there's some problem with the android version. All the items of the list are getting displayed. I have no idea. Can you help me? Thanks once again. 
![screen shot 2016-02-17 at 9 11 36 pm](https://cloud.githubusercontent.com/assets/10998047/13114845/4a774328-d5bb-11e5-972b-ea03897ec256.png)

**Comment by gs-akhan** [comment]
Hi. @sankhadeeproy007 . Sure.. I will definitely look into this. Looks like an issue to me .

**Comment by gs-akhan** [comment]
@sankhadeeproy007 I am sorry I could not check this out. is your issue resolved or do I need to have a look. ?
:)

**Comment by sankhadeeproy007** [comment]
Hi, sadly I couldn't figure out a way to make it work on android properly. But iOS was my main requirement anyways. So thanks for this help! :)

**Comment by gs-akhan** [comment]
Well, then I will fix this any way. Cheers .

**Comment by shivangbtech** [comment]
I am facing the same issue on android. Could you please tell me how to make it working.

**Comment by gs-akhan** [comment]
HI, I've fixed it
Thanks
