### ISSUE TITLE
Close on click elsewhere

### ISSUE THREAD

**Issue by tgoldenberg** [gs-akhan/react-native-select#9]
Is there a `this.refs.select.blur()` function I can call to close the dropdown without selecting a value? This would be a nice feature.

**Comment by gs-akhan** [comment]
@tgoldenberg .. That is nice thing to have . I shall add this by tomorrow. Or if you can add it . Happy to merge it 

Thanks

**Comment by gs-akhan** [comment]
Implemented

this.refs.select1.blur(); will close it. Added in docs too.

Thanks
